services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tws-db2
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./new-data:/var/lib/mysql
    networks:
      - Newnet
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uadmin","-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  flask:
    build:
      context: .
      dockerfile: Dockerfile-multistage
    container_name: flask-app
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: tws-db2
      MYSQL_HOST: mysql
    networks:
      - Newnet
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    restart: always

volumes:
  new-data:

networks:
  Newnet:
