FROM python:3.9-slim AS builder

WORKDIR /app

COPY . .

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y gcc default-libmysqlclient-dev build-essential pkg-config && \
    rm -rf /var/lib/apt/lists/*

RUN pip install mysqlclient
RUN pip install --no-cache-dir -r requirements.txt --target=/apps/deps

# ---------- Runtime Stage ----------
FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libmariadb3 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /apps/deps /app/deps
COPY . .

ENV PYTHONPATH=/app/deps

EXPOSE 5000

CMD ["python", "app.py"]
